name: stage1_teacher_contras_network
use_tb_logger: true
model_type: TeacherContrasModel
scale: 2
crop_border: ~
set_CUDA_VISIBLE_DEVICES: ~
gpu_ids: [3]

# datasets
datasets:
  train:
    name: CUFED
    type: ContrasDataset
    dataroot_in: /home/ilaopi/桌面/zhy/GNNSR-main/GNNSR/datasets/CUFED/train/input/   
    dataroot_ref: /home/ilaopi/桌面/zhy/GNNSR-main/GNNSR/datasets/CUFED/train/ref/
    io_backend:
      type: disk

    gt_size: 160
    use_flip: true
    use_rot: true

    bicubic_model: PIL

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 8
    dataset_enlarge_ratio: 1000
  val:
    name: val_CUFED
    type: ContrasValDataset
    dataroot_in: /home/ilaopi/桌面/zhy/GNNSR-main/GNNSR/datasets/CUFED/test/CUFED5/
    dataroot_ref: /home/ilaopi/桌面/zhy/GNNSR-main/GNNSR/datasets/CUFED/test/CUFED5/
    io_backend:
      type: disk

    ann_file: ./datasets/contras_val.txt

    bicubic_model: PIL

# network structures
network_g:
  type: ContrasExtractorSep

# path
path:
  pretrain_model_g: ~
  strict_load: true
  resume_state: ~

# training settings: learning rate scheme, loss
train:
  lr_g: !!float 1e-3
  lr_scheme: MultiStepLR

  niter: 5000
  warmup_iter: -1  # no warm up
  lr_steps: ~
  lr_gamma: ~

  manual_seed: 10
  margin: 1.0
  safe_radius: 8
  scaling_steps: 1

val:
  val_freq: !!float 5e3
  save_img: True

# logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

dist_params:
  backend: nccl
  port: 29746
